language: python
python:
  - "3.3"
#  - "2.7"
#  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: true 

# # commands to run before script
before_script: 
  - chmod +x do_nothing.sh

# # command to run tests, e.g. python setup.py test
script: 
  - nosetests -v
